# Generated by Django 3.0.2 on 2020-01-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsApp', '0003_products_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_id',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goodsApp.Category'),
        ),
    ]
