# Generated by Django 3.0.2 on 2020-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsApp', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(upload_to='aboutpage_images'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(upload_to='partner_image'),
        ),
    ]
