# Generated by Django 3.0.2 on 2020-01-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsApp', '0007_auto_20200119_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='updated_at',
        ),
    ]
