# Generated by Django 3.0.2 on 2020-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsApp', '0011_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
